#Información del sitio:
site_name: Wiki ColmenaLabs
site_description: Documentación de los proyectos de la Colmena
site_author: 'ColmenaLabs_svq'
site_url: https://github.com/Colm3na/DocsColmena
#Navegación:
nav:
  - Home: index.md
  - Instalación wiki: instalDoc.md
  - ¿Qué es la blockchain?: introblock.md
  - Ethereum:
    - ¿Qué es Ethereum?: ethblock.md
    - Gas: gas.md
    - Sharding: sharding.md
    - State Channels: statechannel.md
    - Plasma: plasma.md
    - Web3.0: web3.md
    - FAQ-ETH2.0: faqeth.md 
  - Meetups:
    - Meetup DAOs: meetdao.md
    - Workshop DAOs con Aragon: daoragon.md
    - Workshop Swarm: swarm.md
    - Workshop Brave publishers: brave.md
    - Workshop ENS: ens.md
    - Workshop ERC20: erc20.md
  - Proof of Stake:
    - ¿Qué es PoS?: pos.md
  - Colony:
    - ¿Qué es Colony?: colony.md
    - ¿Cómo crear una colonia?: createcolony.md
    - ¿Cómo unirse a una colonia?: joincolony.md
    - ¿Cómo crear tareas en Colony?: createtask.md
    - ¿Cómo añadir permisos?: addpermissionsColony.md
  - Bitcoin:
    - Inicio: lightning-index.md
    - Meetup: lightning-network/README.md
    - Bitcoin: lightning-network/1.0_Bitcoin.md
    - SegWit: lightning-network/1.1_SegWit.md
    - LightningNetwork: lightning-network/2_LightningNetwork.md
    - Sidechains de Bitcoin: lightning-network/3_Sidechains_de_Bitcoin.md
    - Enlaces de interés: lightning-network/4_Resources.md
    - Comandos para el despliegue: lightning-network/5_Comandos_para_desplegar_LND.md
    - Instalación nodo LND y primer contacto: lightning-network/6_Guía_definitiva_para_la_instalación_un_nodo_de_LND_y_primeras_interacciones.md
    - Infogramas de LND: lightning-network/7_Infogramas.md
  - Locha: locha.md
  - Kyber: howtokyber.md
  - IPFS: ipfs.md
  - Polkadot: 
    - Inicio: polkadot.md
    - Reclamar tus DOTs: claimDots.md
    - Glosario: glosario.md
  - Kusama:
    - kusama: kusama.md
    - ¿Cómo votar en Kusama?: votekusama.md
  - DAppNode: 
    - Inicio: DAppNodeCosmos.md
    - DappNode+WIFI: DAppNodeWIFI.md
  - Cosmos: 
    - Cosmos: cosmos.md
    - Terminología: terminos.md
    - Gaia: gaia.md
    - Instalación: installgaia.md
    - Mainnet: mainnet.md
    - Gobernanza: governance.md
  - Cyberd: 
    - Inicio: cyberd.md
  - Kava: 
    - Inicio: kava.md
  - Sistemas:
    - Inicio: sistemas.md
    - Ghost: ghost.md
  - Git: git.md
#Configuración del tema: 
theme:
  name: 'material'
  highlightjs: true
  hljs_languages:
      - yaml
      - rust
      - bash
      - json
      - makefile
      - markdown
      - nginx
      - apache
      - python
      - ruby
  feature:
    tabs: false
#Repositorio original.
#Necesario para renderizar el enlace en la superior derecha.
repo_name: 'Colm3na/DocsColmena'
repo_url: 'https://github.com/Colm3na/DocsColmena'
#Enlaces de las redes.
extra:
  social:
    - type: 'github'
      size: 'lg'
      link: 'https://github.com/Colm3na'
    - type: 'twitter'
      size: 'lg'
      link: 'https://twitter.com/ColmenaLabs_svq'
    - type: 'medium'
      size: 'lg'
      link: 'https://medium.com/colmenasvq'
    - type: 'blog'
      syze: 'lg'
      link: 'https://blog.colmenalabs.org/'
